name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create PEM file
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2-key.pem
          chmod 600 ec2-key.pem

      - name: Deploy via SSH
        run: |
          scp -i ec2-key.pem -o StrictHostKeyChecking=no index.html ec2-user@${{ secrets.EC2_HOST }}:/home/deploy-html-with-ga/
        # replace `ec2-user` with your actual EC2 username
