name: Deploy Website

on:
  push:
    branches:
      - main # Or your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write private key
        run: |
          echo "${{ secrets.IQBAL_KEYPAIR_PEM }}" > iqbal-keypair.pem
          chmod 400 iqbal-keypair.pem

      - name: Deploy to server
        run: |
          scp -i iqbal-keypair.pem -o StrictHostKeyChecking=no simple-html/index.html ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/tmp/index.html